version: '3.8'
services:
    banking-api:
        image: banking-api:latest
        container_name: banking-api
        ports:
            - "8000:8000"
        build:
            context: .
            dockerfile: .docker/production/Dockerfile
        restart: unless-stopped
        working_dir: /app
        environment:
            DB_HOST: banking-db
            DB_PORT: 3306
            DB_DATABASE: banking-system
            DB_USERNAME: laravel
            DB_PASSWORD: secret
        depends_on:
            - banking-db
        networks:
            - banking-network

    banking-db:
        image: mysql:8.0
        container_name: banking-db
        environment:
            MYSQL_DATABASE: banking-system
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - banking-db-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - banking-network

networks:
    banking-network:
        driver: bridge

volumes:
    banking-db-data:
        driver: local
#    banking-redis-data:
#        driver: local
